
# -----------------CONTACTO-------------------
###
POST  http://localhost:3000/api/contacto
Content-Type: application/json

{
    "nombre": "Carolina Herrera",
    "email": "developer@gmail.com",
    "edad":"27",
    "pais": "Uruguay",
    "comentario":"Hola quiero mas info!+5493454093473"
}
###
GET  http://localhost:3000/api/contacto
